version: '3.4'

networks:
  movie-api-project:

services:
  movie-api-db:
    container_name: movieapi-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=001@postgres
      - POSTGRES_DB=MoviesAPIDb 
    networks:
      - movie-api-project
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data 
    



  simplemovieapi:
    container_name: movies-api
    image: ${DOCKER_REGISTRY-}simplemovieapi
    build:
      context: .
      dockerfile: SimpleMovieAPI/Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - "movie-api-db"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=001@postgres;Server=movie-api-db;Port=5432;Database=MoviesAPIDb;IntegratedSecurity=true
      - ASPNETCORE_URLS=http://+:80

     
    networks:
      - movie-api-project

volumes:
   app_data: